config/routes.rb
Rails.application.routes.draw do

  root to: "restaurants#index"

  resources :restaurants, shallow: true do
    resources :reviews
      resources :endorsements
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  belongs_to :user

  has_many :reviews, dependent: :destroy

  validates :name, length: {minimum: 3}, uniqueness: true

  def already_Reviewed?(user)
    return Review.where(user: user, restaurant: self).first
  end

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :restaurant
  belongs_to :user

  has_many :endorsements

  validates :rating, inclusion: (1..5)

  validates :user_id, uniqueness: {scope: :restaurant_id, message: "You can't slag off a restaurant more than once" }

  def can_you_delete?(user)
    self.user == user
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :restaurants
  has_many :reviews

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    redirect_to restaurants_path
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

#intention to create a record
  def new
    @restaurant = Restaurant.new
  end

#creates a record and then redirects to another place
  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

# define which params we are going to allow us to pass to controller, without this security flaw.
  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

# intention to alter record
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

# record is actually updated
  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    #@restaurant.reviews.create(review_params)
    @restaurant.reviews.create(review_params.merge({user:current_user}))
    redirect_to restaurants_path
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

  def destroy
    # why do we need to pass in restaurant when we don't use it?
    @review = Review.find(params[:id])
    if @review.can_you_delete?(current_user)
      @review.destroy
      flash[:notice] = 'Review deleted successfully'
      redirect_to '/restaurants'
    else
      flash[:notice] = "can't delete another review"
      redirect_to '/restaurants'
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    '★' * rating.round + "☆" * remainder
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="css/styles.css">
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Sign in', new_user_session_path %>
	<%= link_to 'Sign in with Facebook', user_omniauth_authorize_path(:facebook) %>

<!--  Finally, if you want to allow your users to cancel sign up with Facebook, you can redirect them to
 "cancel_user_registration_path". This will remove all session data starting with "devise." and the new_with_session hook
 above will no longer be called.  -->


<% end %>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
      <h2><%=link_to  restaurant.name, restaurant_path(restaurant) %></h2>
        <h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
        <% if user_signed_in? %>
          <% if restaurant.user_id == current_user.id %>
            <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
            <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
          <% end %>
          <% if !restaurant.already_Reviewed?(current_user) %>
            <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
          <% end %>
        <% end %>
      <% if restaurant.reviews.any? %>
        <ul>
          <% restaurant.reviews.each do |review| %>
            <li>
              <%= review.thoughts %>, <%= review.rating %>
              <p> <%= pluralize review.endorsements.count, 'endorsement' %></p>
              <% if user_signed_in? %>
                <%if review.user_id == current_user.id%>
                  <%= link_to "Delete Review", review_path(review), method: :delete %>
                <% end %>
              <% end %>
      			</li>
      		<% end %>
      	</ul>
      <% end %>
  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<% if user_signed_in? %>
  <%= link_to "Add a restaurant", new_restaurant_path %>
<% end %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
	<section id="errors">
		<h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2> 
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</section>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>